target 'Testing' do
    use_frameworks!
    
    pod 'RxSwift'
    pod 'RxCocoa'
    
    target 'TestingTests' do
        inherit! :search_paths
        pod 'RxTest'
        pod 'RxBlocking'
    end
end
